"""complete_schema

Revision ID: d1d07f806e17
Revises: 
Create Date: 2025-12-07 18:19:41.611164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1d07f806e17'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('departments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('semesters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'FACULTY', name='user_role'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('classrooms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('room_number', sa.String(length=20), nullable=False),
    sa.Column('building_id', sa.Uuid(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('LECTURE_HALL', 'LAB', 'SEMINAR', name='room_type'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_id', 'room_number', name='uq_classroom_location')
    )
    op.create_table('courses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('credit_hours', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('lecture_hours', sa.Integer(), nullable=False),
    sa.Column('lab_hours', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('curriculum_year', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('lecture_hours >= 0 AND lab_hours >= 0', name='check_positive_hours'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courses_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_courses_department_id'), ['department_id'], unique=False)

    op.create_table('faculties',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('rank', sa.Enum('PROFESSOR', 'LECTURER', 'ASSISTANT', name='faculty_rank'), nullable=False),
    sa.Column('max_load_hours', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('current_load_hours', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('faculties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faculties_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_faculties_email'), ['email'], unique=True)

    op.create_table('prerequisites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('prerequisite_course_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('course_id != prerequisite_course_id', name='check_no_self_reference'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['prerequisite_course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'prerequisite_course_id', name='uq_course_prerequisite')
    )
    with op.batch_alter_table('prerequisites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prerequisites_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prerequisites_prerequisite_course_id'), ['prerequisite_course_id'], unique=False)

    op.create_table('sections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('semester_id', sa.Uuid(), nullable=False),
    sa.Column('section_number', sa.String(length=10), nullable=False),
    sa.Column('expected_enrollment', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('semester_id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=True),
    sa.Column('faculty_id', sa.Uuid(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_slot', sa.Time(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('session_type', sa.Enum('LECTURE', 'LAB', 'COMBINED', name='session_type'), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['classrooms.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index('ix_faculty_availability', ['faculty_id', 'day_of_week', 'start_slot'], unique=False)
        batch_op.create_index('ix_room_availability', ['room_id', 'day_of_week', 'start_slot'], unique=False)
        batch_op.create_index('ix_student_cohort', ['semester_id', 'day_of_week', 'start_slot'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_student_cohort')
        batch_op.drop_index('ix_room_availability')
        batch_op.drop_index('ix_faculty_availability')

    op.drop_table('sessions')
    op.drop_table('sections')
    with op.batch_alter_table('prerequisites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prerequisites_prerequisite_course_id'))
        batch_op.drop_index(batch_op.f('ix_prerequisites_course_id'))

    op.drop_table('prerequisites')
    with op.batch_alter_table('faculties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faculties_email'))
        batch_op.drop_index(batch_op.f('ix_faculties_department_id'))

    op.drop_table('faculties')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_department_id'))
        batch_op.drop_index(batch_op.f('ix_courses_code'))

    op.drop_table('courses')
    op.drop_table('classrooms')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('semesters')
    op.drop_table('departments')
    op.drop_table('buildings')
    # ### end Alembic commands ###
